name: Crear imagen Docker

on:
  push:
    branches: 
      - '*'
permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: echo "tag=$(jq -r .version package.json)" >> $TAG #asiganr al tag la version del proyecto sacada del package.json

  call-ci-workflow:
    needs: build #para traer el output
    uses: ./.github/workflows/ci-reusable.yml
    with:
      tag: ${{ needs.build.outputs.TAG }} #input para el workflow reusable: la versión del proyecto
