name: Publish to Docker
on:
  workflow_call:
    inputs: 
      tag:
        required: true
        type: string

permissions:
  packages: write
  contents: read
  attestations: write

jobs:
   publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
     
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: eperezstemdo/git-action-project-davie-elisa/angularImage
          tags: "${{ inputs.tag }}snapshot"
        
          
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
