name: Publish to Docker
on:
  workflow_call:
    inputs: 
      tag:
        required: true
        type: string
    secrets:
      dockeruser:
        required: true
      dockerpassword:
        required: true

permissions:
  packages: write
  contents: read
  id-token: write
  attestations: write
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockeruser }}
          password: ${{ secrets.dockerpassword }} 
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dcokerfile
          push: true
          tags: user/app:latest

         
