name: Workflow que realiza la distribución contínua
on:
  workflow_dispatch:

jobs:
  deploy-curl:
    runs-on: ubuntu-latest
      
    steps:
      - name: Deploy
        run: |
          docker run -id -p 8080:80 dboffelli/ngnixtest
          curl localhost:8080
