name: Workflow que realiza la distribución contínua
on:
  workflow_dispatch:

jobs:
  deploy-curl:
    runs-on: ubuntu-latest
      
    steps:
      - name: Deploy
        run: |
          docker run -id -p 8080:80 dboffelli/ngnixtest
          docker ps
          #curl localhost:8080
        #env:
          #GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Curl
        run: |
          curl localhost:8080


