name: Workflow que realiza la distribución contínua
on:
  workflow_dispatch:

jobs:
  deploy-curl:
    runs-on: ubuntu-latest
      
    steps:
      - name: Deploy
        run: |
          docker run -id -p 80:80 --name nombretest dboffelli/ngnixtest
          docker ps
          curl localhost:8080
          curl localhost:80
        #env:
          #GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      #- name: Curl
        #run: |
          #docker exec nombretest curl 0.0.0.0
          #curl localhost:80




