name: Workflow CD reusable
on:
  workflow_call:
    inputs:
      image-to-build:
        required: true
        type: string
permissions:
  packages: write
  contents: read
  id-token: write
  attestations: write
jobs:
  deploy-curl:
    runs-on: ubuntu-latest
    #environment:
      #name: deploy
    #permissions: read-all
    steps:
      - name: Deploy
        run: |
          "docker run -id -p 8080:8080 eperezstemdo/angulaimage:0.0.0-snapshot"
          #${{ inputs.image-to-build }}"
          curl localhost:8080
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
