name: Workflow CD reusable
on:
  workflow_call:
    inputs:
      image-to-build:
        required: true
        type: string
permissions: read-all
jobs:
  deploy-curl:
    runs-on: ubuntu-latest
    #environment:
      #name: deploy
    steps:
      - name: Deploy
        run: |
          "docker run -id -p 8080:8080 ${{ inputs.image-to-build }}"
          curl localhost:8080
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
