name: Workflow que realiza la distribución contínua
on:
  workflow_dispatch:

jobs:
  deploy-curl:
    runs-on: ubuntu-latest
      
    steps:
      - name: Deploy
        run: |
          docker run -id -p 8080:80 dboffelli/ngnixtest
          #curl localhost:8080
        #env:
          #GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
      # Check the following URLs one by one sequentially
          url: localhost:8080


